services:
  mysql:
    image: mysql:8.0
    container_name: tech_blog_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: devpass
      MYSQL_DATABASE: tech_blog
    ports:
      - "3306:3306"
    volumes:
      - tech_blog_db:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
volumes:
  tech_blog_db:
